export const gigantamaxMap: Record<string, string> = {
  charizard: "charizard-gmax",
  pikachu: "pikachu-gmax",
  eevee: "eevee-gmax",
  meowth: "meowth-gmax",
  butterfree: "butterfree-gmax",
  gengar: "gengar-gmax",
  machamp: "machamp-gmax",
  kingler: "kingler-gmax",
  lapras: "lapras-gmax",
  snorlax: "snorlax-gmax",
  alcremie: "alcremie-gmax",
  appletun: "appletun-gmax",
  blastoise: "blastoise-gmax",
  cinderace: "cinderace-gmax",
  coalossal: "coalossal-gmax",
  copperajah: "copperajah-gmax",
  corviknight: "corviknight-gmax",
  drednaw: "drednaw-gmax",
  duraludon: "duraludon-gmax",
  flapple: "flapple-gmax",
  garbodor: "garbodor-gmax",
  grimmsnarl: "grimmsnarl-gmax",
  hatterene: "hatterene-gmax",
  inteleon: "inteleon-gmax",
  melmetal: "melmetal-gmax",
  orbeetle: "orbeetle-gmax",
  rillaboom:"rillaboom-gmax",
  sandaconda:"sandaconda-gmax",
  toxtricity:"toxtricity-gmax",
  urshifu:"urshifu-gmax",
  venusaur:"venusaur-gmax"
}
